name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  php:
    uses: nubitio/.github/.github/workflows/reusable-ci-php.yml@main
    with:
      php-version: "8.4"
